FROM python:3.11-slim

WORKDIR /app

COPY requirements.frontend.txt .
RUN pip install --no-cache-dir -r requirements.frontend.txt

COPY ui/start.py ./ui/start.py

EXPOSE 8501

CMD ["streamlit", "run", "ui/start.py", "--server.port=8501", "--server.address=0.0.0.0", "--server.headless=true"]